# coding: utf-8

"""
    WebScraping.AI

    WebScraping.AI scraping API provides GPT-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.1.3
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webscraping_ai.api.selected_html_api import SelectedHTMLApi


class TestSelectedHTMLApi(unittest.TestCase):
    """SelectedHTMLApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SelectedHTMLApi()

    def tearDown(self) -> None:
        pass

    def test_get_selected(self) -> None:
        """Test case for get_selected

        HTML of a selected page area by URL and CSS selector
        """
        pass

    def test_get_selected_multiple(self) -> None:
        """Test case for get_selected_multiple

        HTML of multiple page areas by URL and CSS selectors
        """
        pass


if __name__ == '__main__':
    unittest.main()
