# coding: utf-8

"""
    WebScraping.AI

    A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: support@webscraping.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import webscraping_ai
from webscraping_ai.api.html_api import HTMLApi  # noqa: E501
from webscraping_ai.rest import ApiException


class TestHTMLApi(unittest.TestCase):
    """HTMLApi unit test stubs"""

    def setUp(self):
        self.api = webscraping_ai.api.html_api.HTMLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_html(self):
        """Test case for get_html

        Page HTML by URL  # noqa: E501
        """
        pass

    def test_post_html(self):
        """Test case for post_html

        Page HTML by URL with POST request to the target page  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
