# coding: utf-8

"""
    WebScraping.AI

    A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@webscraping.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import webscraping_ai
from webscraping_ai.api.selected_html_api import SelectedHTMLApi  # noqa: E501
from webscraping_ai.rest import ApiException


class TestSelectedHTMLApi(unittest.TestCase):
    """SelectedHTMLApi unit test stubs"""

    def setUp(self):
        self.api = webscraping_ai.api.selected_html_api.SelectedHTMLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_selected(self):
        """Test case for get_selected

        HTML of a selected page area by URL and CSS selector  # noqa: E501
        """
        pass

    def test_get_selected_multiple(self):
        """Test case for get_selected_multiple

        HTML of multiple page areas by URL and CSS selectors  # noqa: E501
        """
        pass

    def test_post_selected(self):
        """Test case for post_selected

        HTML of a selected page areas by URL and CSS selector, with POST request to the target page  # noqa: E501
        """
        pass

    def test_post_selected_multiple(self):
        """Test case for post_selected_multiple

        HTML of multiple page areas by URL and CSS selectors, with POST request to the target page  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
