# coding: utf-8

"""
    WebScraping.AI

    WebScraping.AI scraping API provides LLM-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.2.0
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webscraping_ai.api.html_api import HTMLApi


class TestHTMLApi(unittest.TestCase):
    """HTMLApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HTMLApi()

    def tearDown(self) -> None:
        pass

    def test_get_html(self) -> None:
        """Test case for get_html

        Page HTML by URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
