# coding: utf-8

"""
    WebScraping.AI

    WebScraping.AI scraping API provides GPT-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.1.3
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webscraping_ai.api.text_api import TextApi


class TestTextApi(unittest.TestCase):
    """TextApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TextApi()

    def tearDown(self) -> None:
        pass

    def test_get_text(self) -> None:
        """Test case for get_text

        Page text by URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
