# coding: utf-8

"""
    WebScraping.AI

    WebScraping.AI scraping API provides LLM-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.2.0
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webscraping_ai.api.ai_api import AIApi


class TestAIApi(unittest.TestCase):
    """AIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AIApi()

    def tearDown(self) -> None:
        pass

    def test_get_fields(self) -> None:
        """Test case for get_fields

        Extract structured data fields from a web page
        """
        pass

    def test_get_question(self) -> None:
        """Test case for get_question

        Get an answer to a question about a given web page
        """
        pass


if __name__ == '__main__':
    unittest.main()
