# coding: utf-8

"""
    WebScraping.AI

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import webscraping_ai
from webscraping_ai.models.scrapped_page import ScrappedPage  # noqa: E501
from webscraping_ai.rest import ApiException

class TestScrappedPage(unittest.TestCase):
    """ScrappedPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ScrappedPage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = webscraping_ai.models.scrapped_page.ScrappedPage()  # noqa: E501
        if include_optional :
            return ScrappedPage(
                size_bytes = 56, 
                html = '0', 
                status = 56, 
                status_message = '0'
            )
        else :
            return ScrappedPage(
        )

    def testScrappedPage(self):
        """Test ScrappedPage"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
