# coding: utf-8

# flake8: noqa

"""
    WebScraping.AI

    WebScraping.AI scraping API provides LLM-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.2.0
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "3.2.0"

# import apis into sdk package
from webscraping_ai.api.ai_api import AIApi
from webscraping_ai.api.account_api import AccountApi
from webscraping_ai.api.html_api import HTMLApi
from webscraping_ai.api.selected_html_api import SelectedHTMLApi
from webscraping_ai.api.text_api import TextApi

# import ApiClient
from webscraping_ai.api_response import ApiResponse
from webscraping_ai.api_client import ApiClient
from webscraping_ai.configuration import Configuration
from webscraping_ai.exceptions import OpenApiException
from webscraping_ai.exceptions import ApiTypeError
from webscraping_ai.exceptions import ApiValueError
from webscraping_ai.exceptions import ApiKeyError
from webscraping_ai.exceptions import ApiAttributeError
from webscraping_ai.exceptions import ApiException

# import models into sdk package
from webscraping_ai.models.account import Account
from webscraping_ai.models.error import Error
