# coding: utf-8

# flake8: noqa

"""
    WebScraping.AI

    A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@webscraping.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "2.0.0"

# import apis into sdk package
from webscraping_ai.api.html_api import HTMLApi
from webscraping_ai.api.selected_html_api import SelectedHTMLApi

# import ApiClient
from webscraping_ai.api_client import ApiClient
from webscraping_ai.configuration import Configuration
from webscraping_ai.exceptions import OpenApiException
from webscraping_ai.exceptions import ApiTypeError
from webscraping_ai.exceptions import ApiValueError
from webscraping_ai.exceptions import ApiKeyError
from webscraping_ai.exceptions import ApiException
# import models into sdk package
from webscraping_ai.models.error import Error
from webscraping_ai.models.page_error import PageError

