# coding: utf-8

# flake8: noqa

"""
    WebScraping.AI

    WebScraping.AI scraping API provides LLM-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

    The version of the OpenAPI document: 3.2.1
    Contact: support@webscraping.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "3.2.0"

# Define package exports
__all__ = [
    "AIApi",
    "AccountApi",
    "HTMLApi",
    "SelectedHTMLApi",
    "TextApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Account",
    "Error",
]

# import apis into sdk package
from webscraping_ai.api.ai_api import AIApi as AIApi
from webscraping_ai.api.account_api import AccountApi as AccountApi
from webscraping_ai.api.html_api import HTMLApi as HTMLApi
from webscraping_ai.api.selected_html_api import SelectedHTMLApi as SelectedHTMLApi
from webscraping_ai.api.text_api import TextApi as TextApi

# import ApiClient
from webscraping_ai.api_response import ApiResponse as ApiResponse
from webscraping_ai.api_client import ApiClient as ApiClient
from webscraping_ai.configuration import Configuration as Configuration
from webscraping_ai.exceptions import OpenApiException as OpenApiException
from webscraping_ai.exceptions import ApiTypeError as ApiTypeError
from webscraping_ai.exceptions import ApiValueError as ApiValueError
from webscraping_ai.exceptions import ApiKeyError as ApiKeyError
from webscraping_ai.exceptions import ApiAttributeError as ApiAttributeError
from webscraping_ai.exceptions import ApiException as ApiException

# import models into sdk package
from webscraping_ai.models.account import Account as Account
from webscraping_ai.models.error import Error as Error

