# coding: utf-8

# flake8: noqa
"""
    WebScraping.AI

    A client for https://webscraping.ai API. It provides Chrome JS rendering, rotating proxies and HTML parsing for web scraping.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from webscraping_ai.models.scrapped_page import ScrappedPage
